site_name: Modelo de Ising Cuántico Unidimensional

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Modelo de Ising G02: index.md
  - Clase Hamiltoniano: hamiltoniano.md
  - Runge-Kutta 4: rk4.md
  - Diagonalización: diag.md
  - Resultados Python: resultadosPy.md
  - Resultados C++: resultadosCpp.md
  - Conclusiones: conclusiones.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

